#!/bin/bash
# Pull the latest changes from git, update requirements, migrate database, run frontend scripts
echo "Force Pull from git..."
git fetch --all
git reset --hard origin/master
echo "Updating Composer..."
composer update --no-dev
composer dump-autoload
echo "Migrating database..."
php artisan migrate
echo "Running Prod versions of files"
npm run prod
echo "Clear app cache..."
php artisan optimize
php artisan cache:clear
php artisan route:cache
php artisan view:clear
php artisan config:cache
php artisan cache:custom
echo "Set update script executable..."
chmod 0700 update
echo "Permissions for storage"
chmod 0777 -R ./storage
echo "All done."